**Задача 1.** Выполнить операции над матрицами.


$$
A = \begin{pmatrix}
1 & 2 & 1\\
-2 & 1 & 1\\
\end{pmatrix}
$$

$$
B= \begin{pmatrix}
3 & 1\\
-1 & 0\\
2 & 4
\end{pmatrix}
$$

$$
С= \begin{pmatrix}
-2 & 2\\
1 & -1\\
1 & 2
\end{pmatrix}
$$

Найти: A+2*B, B+2*C

In [2]:
import numpy as np

In [6]:
A = np.matrix([[1, 2, 1], [-2, 1, 1]])
B = np.matrix([[3, 1], [-1, 0], [2, 4]])
C = np.matrix([[-2, 2], [1, -1], [1, 2]])

# Поскольку математически складывать матрицы разных порядков нельзя, транспонируем матрицу B с использованием Numpy
result1 = np.add(A, np.dot(np.transpose(B), 2))
print('A+2B = \n', result1, '\n')
# Складываем матрицы одного порядка
result2 = np.add(B, np.dot(C, 2))
print('B+2C = \n', result2)

A+2B = 
 [[7 0 5]
 [0 1 9]] 

B+2C = 
 [[-1  5]
 [ 1 -2]
 [ 4  8]]


**Задача 2.** Создать матрицу рзмером 8х8 элементов, состоящую из нулей. Заполнить эту матрицу значениями, расположенными в шахматном порядке.

In [ ]:
a = np.zeros((8, 8))

a[::2, ::2] = 1
a[1::2, 1::2] = 1

print('Матрица\n', a)

Матрица
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**Задача 3*.**
1. Сформировать два вектора: первый длиной 15 элементов со значениями от 0 до 1,4 с шагом 0,1; второй - длиной 6 элементов со значениями от 1 до 6.
2. Преобразовать первый вектор в матрицу 5х3, а второй - в матрицу 3Х2. Выполнить перемножение этих матриц. Сами матрицы и результат их перемножения вывести на экран.

In [ ]:
# Part 1
a = np.arange(0, 1.5, 0.1)
b = np.arange(1, 7)

print('Первый вектор\n', a)
print('Второй вектор\n', b)

Первый вектор
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4]
Второй вектор
 [1 2 3 4 5 6]


In [ ]:
# Part 2

a1 = a.reshape(5,3)
b1 = b.reshape(3,2)
print('Первый вектор преобразованный в матрицу\n', a1)
print('Второй вектор преобразованный в матрицу\n', b1)
# Обращаем внимание, что у нас вектора, т.е. используем скалярное произведение
c1 = a1@b1
print('Произведение векторов\n', c1)
# или так
с1 = np.matmul(a1, b1)
print('Произведение векторов\n', c1)

Первый вектор преобразованный в матрицу
 [[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
Второй вектор преобразованный в матрицу
 [[1 2]
 [3 4]
 [5 6]]
Произведение векторов
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]
Произведение векторов
 [[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


**Задача 4*.**
1. Сформировать вектор из целых чисел (тип элементов должен быть int32) размерностью 36 и значениями 1, 3, 5, 7, ... и так далее.
2. Выделить из этого вектора все элементы со значениями кратными 3. Вывести результат на экран (исходный вектор и с кратными числами).

In [ ]:
# Part 1
a = np.arange(1, 72, 2, dtype=np.int32)

print('Вектор\n', a)
print('Проверяем размерность вектора:\n', len(a))


Вектор
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Проверяем размерность вектора:
 36


In [ ]:
# Part 2

#Если проанализировать массив, то каждое 3е значение начиная с 3 делится на 3 нацело, соответственно:
b = a[1::3]
print('Исходный вектор\n', a)
print('Вектор с кратными числами\n', b)

# или просто выведем значения, которые деляться на 3 без остатка
b = a[a % 3 == 0]
print('Вектор с кратными числами\n', b)


Исходный вектор
 [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
Вектор с кратными числами
 [ 3  9 15 21 27 33 39 45 51 57 63 69]
Вектор с кратными числами
 [ 3  9 15 21 27 33 39 45 51 57 63 69]
